WIP: add test dependencies (JUnit version conflict)
Added spring-boot-starter-test but has JUnit 4.
Want to use JUnit 5 instead.

Error: Mix of JUnit 4 and 5 annotations

TODO: Exclude JUnit 4, use only JUnit 5